name: Generate Language Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install @octokit/rest

      - name: Generate language stats
        run: node scripts/generate-languages.js
        env:
          GH_TOKEN: ${{ secrets.METRICS_TOKEN }}

      - name: Commit SVG
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add languages.svg
          git commit -m "update languages stats" || echo "no changes"
          git push